#!/bin/bash
#SBATCH -o splicing.%j.out
#SBATCH -e splicing.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=$aaron.taylor@jax.org
#SBATCH --mem=20000
#SBATCH --cpus-per-task=4
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 3-00:00:00 

cd $SLURM_SUBMIT_DIR
date;hostname;pwd

module load singularity

curl -fsSL get.nextflow.io | bash

./nextflow run /projects/lau-lab/ataylor/igct/sarek/main.nf \
--outdir ${SLURM_SUBMIT_DIR} \
-profile sumner -resume \
-with-trace trace.txt \
--input /projects/lau-lab/ataylor/igct/sra_reads_sarekAllSamples.tsv \
--sra true \
--tools FreeBayes \
--genome GRCh38 \
--key_file /projects/lau-lab/ataylor/igct/IGCT.Apr7key.ngc \
--intervals /projects/lau-lab/ataylor/igct/MHC.AllGeneRegions.Unique.Sorted.3Column.bed
