#!/bin/bash
#SBATCH -o splicing.%j.out
#SBATCH -e splicing.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=$aaron.taylor@jax.org
#SBATCH --mem-per-cpu=4000
#SBATCH --cpus-per-task=8
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -t 2-00:00:00 

cd /projects/lau-lab/ataylor/igct/
date;hostname;pwd

module load singularity

curl -fsSL get.nextflow.io | bash

./nextflow run /projects/lau-lab/ataylor/igct/sarek/main.nf \
--outdir /projects/lau-lab/ataylor/igct/results/ \
-profile sumner,base -resume \
-with-trace trace.txt \
--input /projects/lau-lab/ataylor/igct/sra_reads_sarekAllSamples.tsv \
--sra true \
--tools FreeBayes \
--genome GRCh38 \
--key_file /projects/lau-lab/ataylor/igct/IGCT.Apr7key.ngc \
--intervals /projects/lau-lab/ataylor/igct/MHC.AllGeneRegions.Unique.Sorted.3Column.bed
--max_cpus 16 \
--max_memory 64.GB
